// Generated by CoffeeScript 1.6.3
(function() {
  var pudu;

  pudu = {};

  pudu.stickerKeyHost = 'http://pudux.googlecode.com/git/k/';

  pudu.stickerImgHost = 'http://pudux.googlecode.com/git/i/';

  pudu.defaultSetting = {
    version: '1.1.0',
    selectedStickers: ['sticker1', 'sticker1001', 'sticker1002', 'sticker1003', 'sticker1004', 'sticker1038'],
    lastUsedEmoSet: '#pudu-emo-smiley'
  };

  pudu.setLocalStorage = function(data, func) {
    if (func == null) {
      func = function() {};
    }
    return chrome.storage.local.set(data, func);
  };

  pudu.getLocalStorage = function(func) {
    return chrome.storage.local.get(func);
  };

  pudu.clearLocalStorage = function(func) {
    if (func == null) {
      func = function() {};
    }
    return chrome.storage.local.clear(func);
  };

  pudu.removeLocalStorage = function(key, func) {
    if (func == null) {
      func = function() {};
    }
    return chrome.storage.local.remove(key, func);
  };

  pudu.getExtensionUrl = function(uri) {
    return chrome.extension.getURL(uri);
  };

  pudu.getLocalStorage(function(items) {
    if (items.version === void 0) {
      return pudu.setLocalStorage(pudu.defaultSetting, function() {
        return window.location.href = window.location.href;
      });
    } else if (pudu.versionCompare(items.version, pudu.defaultSetting.version) === -1) {
      items.version = pudu.defaultSetting.version;
      return pudu.setLocalStorage($.extend(pudu.defaultSetting, items), function() {
        return window.location.href = window.location.href;
      });
    }
  });

  window.pudu = pudu;

}).call(this);

/*
//@ sourceMappingURL=config.map
*/
