// Generated by CoffeeScript 1.6.3
(function() {
  var $addReplyButton, $bottomAddComment, $bottomPagination, $browseTable, $browseTableAdded, $browseTableComm, $browseTableFiles, $browseTableHeader, $browseTableLeechers, $browseTableName, $browseTablePeers, $browseTableRow, $browseTableSeeders, $browseTableSize, $browseTableSnatched, $browseTableType, $browseTableUppedby, $commentsBody, $commentsBox, $commentsContent, $commentsEditLink, $commentsHeader, $commentsLikeLink, $commentsPmLink, $commentsQuoteLink, $commentsTable, $commentsTableInner, $commentsUser, $content, $forumsTable, $forumsTableHeader, $forumsTableRow, $forumsTableRowForum, $forumsTableRowLastTopic, $forumsTableRowPosts, $forumsTableRowTopics, $header, $menu, $topAddComment, $topPagination, $topicTable, $topicTableHeader, $topicTableRow, $topicTableRowAuthor, $topicTableRowLastPost, $topicTableRowReplies, $topicTableRowTopic, $topicTableRowViews, $torrentCommentLink, html, p, page, pudu, title, url, v;

  pudu = window.pudu;

  url = window.location.href;

  page = {
    viewtopic: url.indexOf('/forums.php?action=viewtopic') !== -1 || url.indexOf('/markets.php?action=viewtopic') !== -1,
    viewforum: url.indexOf('/forums.php?action=viewforum') !== -1 || url.indexOf('/markets.php?action=viewforum') !== -1 || url.indexOf('/markets.php?action=viewall') !== -1,
    forums: (url.indexOf('/forums.php') !== -1 || url.indexOf('/markets.php') !== -1) && url.indexOf('?action=') === -1,
    browse: url.indexOf('/browse.php') !== -1,
    details: url.indexOf('/details.php') !== -1
  };

  $menu = $('.outer:first');

  $content = $('.outer:last');

  $header = $('h1:first');

  if (page.viewtopic || page.viewforum) {
    $topPagination = $('h1+p:first');
    $bottomPagination = $('table+p:first');
  }

  if (page.viewtopic || page.details) {
    $commentsTable = $('table.main[width="750"]');
    $commentsContent = $('.comment');
    $commentsTableInner = $commentsTable.find('table:first');
    $commentsBox = $commentsTableInner.find('a[name] > table').parent();
    $commentsHeader = $commentsTableInner.find('p.sub > table');
    $commentsBody = $commentsBox.find('>table.main');
    $commentsUser = $commentsHeader.find('a[href^="userdetails.php"]');
    $commentsPmLink = $commentsHeader.find('a[href^="sendmessage.php"]');
    $commentsQuoteLink = $commentsHeader.find('a[href^="?action=quotepost"]');
    $commentsLikeLink = $commentsHeader.find('a[href^="forums.php?action=likes"]');
    $commentsEditLink = $commentsHeader.find('a[href^="forums.php?action=editpost"]');
    $torrentCommentLink = $('a[href^="comment.php?action=add"]');
  }

  if (page.viewtopic) {
    $addReplyButton = $('input[value="Add Reply"]');
  }

  if (page.forums) {
    $forumsTable = $('h1+p+table, h1+table');
    $forumsTableRow = $forumsTable.find('tbody > tr');
    $forumsTableHeader = $forumsTable.find('tbody > tr:eq(0)');
    $forumsTableRowForum = $forumsTableRow.find('> td:eq(0)');
    $forumsTableRowTopics = $forumsTableRow.find('> td:eq(1)');
    $forumsTableRowPosts = $forumsTableRow.find('> td:eq(2)');
    $forumsTableRowLastTopic = $forumsTableRow.find('> td:eq(3)');
  }

  if (page.details) {
    $topPagination = $('p[align="center"]:eq(1)');
    $bottomPagination = $('p[align="center"]:eq(2)');
    $topAddComment = $('p[align="center"]:eq(0) > a');
    $bottomAddComment = $('p[align="center"]:eq(3) > a');
    $commentsHeader = $('p.sub');
    $commentsBody = $('p.sub+table');
    $commentsContent = $commentsBody.find('td.text');
    $commentsUser = $commentsHeader.find('a[href^="userdetails.php"]');
  }

  if (page.viewforum) {
    $topicTable = $topPagination.next();
    $topicTableRow = $topicTable.find('tbody > tr');
    $topicTableHeader = $topicTable.find('tbody > tr:eq(0)');
    $topicTableRowTopic = $topicTableRow.find('> td:eq(0)');
    $topicTableRowReplies = $topicTableRow.find('> td:eq(1)');
    $topicTableRowViews = $topicTableRow.find('> td:eq(2)');
    $topicTableRowAuthor = $topicTableRow.find('> td:eq(3)');
    $topicTableRowLastPost = $topicTableRow.find('> td:eq(4)');
  }

  if (page.browse) {
    $topPagination = $('p[align="center"]:eq(1)');
    $bottomPagination = $('p[align="center"]:eq(2)');
    $browseTable = $topPagination.next();
    $browseTableRow = $browseTable.find('tbody > tr');
    $browseTableHeader = $browseTable.find('tbody > tr:eq(0)');
    $browseTableType = $browseTableRow.find('> td:eq(0)');
    $browseTableName = $browseTableRow.find('> td:eq(1)');
    $browseTableFiles = $browseTableRow.find('> td:eq(2)');
    $browseTableComm = $browseTableRow.find('> td:eq(3)');
    $browseTableAdded = $browseTableRow.find('> td:eq(4)');
    $browseTableSize = $browseTableRow.find('> td:eq(5)');
    $browseTableSnatched = $browseTableRow.find('> td:eq(6)');
    $browseTablePeers = $browseTableRow.find('> td:eq(7)');
    $browseTableSeeders = $browseTableRow.find('> td:eq(8)');
    $browseTableLeechers = $browseTableRow.find('> td:eq(9)');
    $browseTableUppedby = $browseTableRow.find('> td:eq(10)');
  }

  for (p in page) {
    v = page[p];
    if (v === true) {
      $('body').addClass("pudu-page-" + p);
    }
  }

  $menu.addClass('pudu-menu');

  $content.addClass('pudu-content');

  if (page.viewtopic || page.details || page.browse) {
    $topPagination.addClass('pudu-top-pagination');
    $bottomPagination.addClass('pudu-bottom-pagination');
  }

  if (page.viewtopic || page.details) {
    $commentsTable.addClass('pudu-comments-table');
    $commentsTableInner.addClass('pudu-comments-table-inner');
    $commentsBox.addClass('pudu-comments-box');
    $commentsHeader.addClass('pudu-comments-header');
    $commentsContent.addClass('pudu-comments-content');
    $commentsBody.addClass('pudu-comments-body');
    $commentsUser.addClass('pudu-comments-user');
    $commentsPmLink.addClass('pudu-comments-pm-link');
    $commentsQuoteLink.addClass('pudu-comments-quote-link');
    $commentsLikeLink.addClass('pudu-comments-like-link');
    $commentsEditLink.addClass('pudu-comments-edit-link');
  }

  if (page.forums) {
    $forumsTable.addClass('pudu-forums-table');
    $forumsTableRow.addClass('pudu-forums-table-row');
    $forumsTableHeader.removeClass('pudu-forums-table-row').addClass('pudu-forums-table-header');
    $forumsTableRowForum.addClass('pudu-forums-table-row-forum');
    $forumsTableRowTopics.addClass('pudu-forums-table-row-topic');
    $forumsTableRowPosts.addClass('pudu-forums-table-row-posts');
    $forumsTableRowLastTopic.addClass('pudu-forums-table-row-lasttopic');
  }

  if (page.details) {
    $topAddComment.addClass('pudu-top-add-comment');
    $bottomAddComment.addClass('pudu-bottom-add-comment');
  }

  if (page.viewforum) {
    $topicTable.addClass('pudu-topic-table');
    $topicTableRow.addClass('pudu-topic-table-row');
    $topicTableHeader.removeClass('pudu-topic-table-row').addClass('pudu-topic-table-header');
    $topicTableRowTopic.addClass('pudu-topic-table-row-topic');
    $topicTableRowReplies.addClass('pudu-topic-table-row-repiles');
    $topicTableRowViews.addClass('pudu-topic-table-row-views');
    $topicTableRowAuthor.addClass('pudu-topic-table-row-author');
    $topicTableRowLastPost.addClass('pudu-topic-table-row-lastpost');
  }

  if (page.browse) {
    $browseTable.addClass('pudu-browse-table');
    $browseTableRow.addClass('pudu-browse-table-row');
    $browseTableHeader.removeClass('pudu-browse-table-row').addClass('pudu-browse-table-header');
    $browseTableType.addClass('pudu-browse-table-row-type');
    $browseTableName.addClass('pudu-browse-table-row-name');
    $browseTableFiles.addClass('pudu-browse-table-row-file');
    $browseTableComm.addClass('pudu-browse-table-row-comm');
    $browseTableAdded.addClass('pudu-browse-table-row-added');
    $browseTableSize.addClass('pudu-browse-table-row-size');
    $browseTableSnatched.addClass('pudu-browse-table-row-snatched');
    $browseTablePeers.addClass('pudu-browse-table-row-peers');
    $browseTableSeeders.addClass('pudu-browse-table-row-seeders');
    $browseTableLeechers.addClass('pudu-browse-table-row-leechers');
    $browseTableUppedby.addClass('pudu-browse-table-row-uppedby');
  }

  if (page.viewtopic) {
    $('a[href="#top"]').hide();
    $commentsBox.css('backgroundColor', $commentsHeader.css('backgroundColor'));
  }

  if (page.details) {
    $topAddComment.attr('href', '#pudu-quick-comment');
  }

  if (page.viewforum) {
    $('.pudu-topic-table-row > td, .pudu-topic-table-header > td').css('borderColor', $('.pudu-topic-table-header > td:first').css('backgroundColor'));
  }

  if (page.browse) {
    $('.pudu-browse-table-row > td, .pudu-browse-table-header > td').css('borderColor', $('.pudu-browse-table-header > td:first').css('backgroundColor'));
    $browseTableHeader.find('a').css('color', $browseTableHeader.find('td').css('color'));
    $browseTableRow.find('img[src="pic/xr.gif"], img[src="pic/xl.gif"]').hide();
  }

  if (page.forums) {
    $('.pudu-forums-table-row > td, .pudu-forums-table-header > td').css('borderColor', $('.pudu-forums-table-header > td:first').css('backgroundColor'));
  }

  if (page.forums) {
    $('title').text($header.text());
  }

  if (page.viewforum) {
    $('title').text($header.text());
  }

  if (page.viewtopic) {
    title = $header.text();
    $('title').text(title.substring(title.indexOf('> ') + 2));
    if ($addReplyButton.size() > 0) {
      $bottomPagination.after($(pudu.commentHtml('?action=post', 'topicid', 'body')).find('input[name="topicid"]').val($('input[name="topicid"]').val()).end().html());
    }
    $commentsContent.each(function() {
      var cIndex, html;
      html = $(this).html();
      cIndex = html.indexOf('<br>------------------------<br>');
      if (cIndex !== -1) {
        return $(this).html(html.substring(0, cIndex) + '<div class="hide pudu-comment-signature" >' + html.substring(cIndex) + '</div>');
      }
    });
    $('body').on('keydown', function(e) {
      if (e.ctrlKey && e.altKey) {
        return $('.pudu-comment-signature').toggleClass('hide');
      }
    });
    $commentsBox.each(function() {
      var focus, name, score;
      score = $(this).find('td.embedded[width="99%"] b:last').text();
      name = $(this).attr('name');
      if ((10 >= score && score > 0)) {
        focus = 1;
      } else if ((20 >= score && score > 10)) {
        focus = 2;
      } else if ((30 >= score && score > 20)) {
        focus = 3;
      } else if ((40 >= score && score > 30)) {
        focus = 4;
      } else if (score > 40) {
        focus = 5;
      }
      return $commentsBox.filter("[name='" + name + "']").addClass("focus-" + focus);
    });
    $commentsBox.each(function() {
      var $html, html, name;
      name = $(this).attr('name');
      if (name === 'last') {
        name = $(this).prev().attr('name');
      }
      $header = $(this).find('.pudu-comments-header');
      html = $header.html().replace(' GMT', '').replace("#" + name, '').replace(/\[/g, '').replace(/\]/g, '').replace('--', '-');
      $html = $(html).find('a:not(.pudu-comments-user, .pudu-comments-like-link)').each(function() {
        return $(this).text($(this).text());
      }).end();
      return $header.html($html);
    });
  }

  if (page.details) {
    $('title').text($header.text());
    html = $(pudu.commentHtml('comment.php?action=add', 'tid', 'text')).find('input[name="tid"]').val(pudu.parseUrlQuery().id).end().html() + '<br/>';
    if ($bottomAddComment.size() > 0) {
      $bottomAddComment.before(html);
    } else {
      $topAddComment.before(html);
    }
    $commentsHeader.each(function() {
      var name;
      name = $(this).find('.pudu-comments-user').attr('name').replace('comm', '');
      html = $(this).html().replace(' GMT', '').replace("#" + name, '').replace(/\[/g, '').replace(/\]/g, '').replace('--', '-');
      return $(this).html(html);
    });
  }

  if (page.details || page.viewtopic) {
    $('body').on('click', '#emo div', function(event) {
      event.preventDefault();
      event.stopImmediatePropagation();
      event.stopPropagation();
      pudu.insertAtCaret('pudu-comment-textarea', $(this).data('text'));
      return false;
    });
  }

  if (page.browse) {
    $browseTableName.each(function() {
      var $td, link;
      link = $(this).find('a:first');
      if (link.size() > 0) {
        $td = $(this).siblings('.pudu-browse-table-row-peers').html("<a class='pudu-direct-download' data-url='" + (link.attr('href')) + "' href='javascript:void(0);'>torrent</a>");
      } else {
        $td = $(this).siblings('.pudu-browse-table-row-peers').text('Download');
      }
      return $(this).after($td);
    });
    $('.pudu-direct-download').on('click', function() {
      var _this = this;
      if (!$(this).is('.disable')) {
        $(this).text('loading');
        $('.pudu-direct-download').addClass('disable');
        url = $(this).data('url');
        return $.get(url).done(function(res) {
          window.location.href = $(res).find('a[href^="download.php"]').attr('href');
          $(_this).text('torrent');
          return $('.pudu-direct-download').removeClass('disable');
        }).fail(function() {
          $(_this).text('try again');
          return $('.pudu-direct-download').removeClass('disable');
        });
      }
    });
  }

}).call(this);

/*
//@ sourceMappingURL=pudu.map
*/
