// Generated by CoffeeScript 1.6.3
(function() {
  var STICKER_DIR, dir, fs, img, nameIndex, sName, stickerDir, stickers, stickersName, _i, _len;

  STICKER_DIR = 'C:/Users/Chokchai/Desktop/stickers2/';

  fs = require('fs');

  dir = fs.readdirSync(STICKER_DIR);

  stickers = {};

  stickersName = {};

  nameIndex = [];

  for (_i = 0, _len = dir.length; _i < _len; _i++) {
    stickerDir = dir[_i];
    sName = JSON.parse(fs.readFileSync(STICKER_DIR + stickerDir + '/productInfo.meta')).title.en;
    if (nameIndex.indexOf(sName) === -1) {
      nameIndex.push(sName);
      stickers[stickerDir] = (function() {
        var _j, _len1, _ref, _results;
        _ref = fs.readdirSync(STICKER_DIR + stickerDir + '/');
        _results = [];
        for (_j = 0, _len1 = _ref.length; _j < _len1; _j++) {
          img = _ref[_j];
          if (img.indexOf('tab_') === -1 && img.indexOf('_key') === -1 && img.indexOf('.png') !== -1) {
            _results.push(parseInt(img.split('.').shift()));
          }
        }
        return _results;
      })();
      stickersName[stickerDir] = sName;
    }
  }

  fs.writeFileSync(STICKER_DIR + 'pudu.stickers.js', 'window.pudu.stickers = ' + JSON.stringify(stickers) + '; \n window.pudu.stickersName = ' + JSON.stringify(stickersName));

  console.log('pudu.stickers.js is saved!');

}).call(this);

/*
//@ sourceMappingURL=stickers-nodejs.map
*/
